version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db 
    command: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: realtime_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taikisha
    ports:
      - "5436:5432"
