# Generated by Django 3.2.18 on 2024-03-08 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datahistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(null=True)),
                ('doublecount', models.IntegerField(null=True)),
                ('char', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='datalogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plc_make', models.CharField(choices=[('Mitsubishi', 'Mitsubishi')], max_length=100)),
                ('plc_series', models.CharField(choices=[('Q', 'Q'), ('L', 'L'), ('QnA', 'QnA'), ('iQ-L', 'iQ-L'), ('iQ-R', 'iQ-R')], max_length=100)),
                ('plc_ip', models.CharField(max_length=100)),
                ('plc_port', models.IntegerField()),
                ('plc_communication_type', models.CharField(choices=[('binary', 'binary'), ('ascii', 'ascii')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoadingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanger_number', models.IntegerField()),
                ('live_status', models.IntegerField()),
                ('zone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='plc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_a', models.IntegerField(null=True)),
                ('zone_b', models.IntegerField(null=True)),
                ('zone_c', models.IntegerField(null=True)),
                ('zone_d', models.IntegerField(null=True)),
                ('zone_e', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plcparameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plc_make', models.CharField(choices=[('Mitsubishi', 'Mitsubishi')], max_length=100)),
                ('plc_series', models.CharField(choices=[('Q', 'Q'), ('L', 'L'), ('QnA', 'QnA'), ('iQ-L', 'iQ-L'), ('iQ-R', 'iQ-R')], max_length=100)),
                ('plc_ip', models.CharField(max_length=100)),
                ('plc_port', models.IntegerField()),
                ('plc_communication_type', models.CharField(choices=[('binary', 'binary'), ('ascii', 'ascii')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='word_batch_read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startaddress', models.CharField(max_length=100)),
                ('readsize', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zonedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_zone1', models.JSONField(null=True)),
                ('degrease_zone2', models.JSONField(null=True)),
                ('loading_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.loadingstation')),
            ],
        ),
        migrations.CreateModel(
            name='device_tag_setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('bit', 'bit'), ('int', 'int'), ('dint', 'dint'), ('string', 'string'), ('single-precision', 'single-precision'), ('double-precision', 'double-precision')], max_length=100)),
                ('time', models.CharField(choices=[('1sec', '1sec'), ('5sec', '5sec'), ('60sec', '60sec'), ('10min', '10min')], max_length=100)),
                ('no_of_char', models.IntegerField(null=True)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.datalogger')),
            ],
        ),
        migrations.CreateModel(
            name='datatrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.device_tag_setting')),
            ],
        ),
        migrations.CreateModel(
            name='dataloggerdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.device_tag_setting')),
            ],
        ),
    ]
