# Generated by Django 4.2.7 on 2024-03-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dataloggerdata',
        ),
    ]
