# Generated by Django 4.2.7 on 2024-03-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0004_datapool_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggerConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_enabled', models.BooleanField(choices=[(True, 'True'), (False, 'False')])),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='device_tag_setting',
            name='time',
        ),
        migrations.AddField(
            model_name='device_tag_setting',
            name='logging_interval',
            field=models.CharField(choices=[('5sec', '5sec')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='datapool',
        ),
        migrations.AddField(
            model_name='triggerconfiguration',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.device_tag_setting'),
        ),
        migrations.AddField(
            model_name='device_tag_setting',
            name='trigger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='integer.triggerconfiguration'),
        ),
    ]
