# Generated by Django 4.2.7 on 2024-03-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0006_alter_device_tag_setting_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_tag_setting',
            name='logging_interval',
            field=models.CharField(blank=True, choices=[('5sec', '5sec')], max_length=100, null=True),
        ),
    ]
