# Generated by Django 4.2.7 on 2024-03-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0007_alter_device_tag_setting_logging_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerconfiguration',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
