# Generated by Django 4.2.7 on 2024-03-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0008_triggerconfiguration_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_tag_setting',
            name='logging_interval',
        ),
        migrations.RemoveField(
            model_name='device_tag_setting',
            name='trigger',
        ),
    ]
