# Generated by Django 4.2.7 on 2024-03-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0009_remove_device_tag_setting_logging_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerconfiguration',
            name='trigger_enabled',
        ),
    ]
