# Generated by Django 4.2.7 on 2024-03-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0011_triggerlogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triggerlogger',
            name='address',
        ),
        migrations.AddField(
            model_name='triggerlogger',
            name='tag',
            field=models.IntegerField(null=True),
        ),
    ]
