# Generated by Django 4.2.7 on 2024-03-17 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0012_remove_triggerlogger_address_triggerlogger_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggerloggers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='triggerconfiguration',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Triggerlogger',
        ),
        migrations.AddField(
            model_name='triggerloggers',
            name='triggertag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.triggerconfiguration'),
        ),
    ]
