# Generated by Django 4.2.7 on 2024-03-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0013_triggerloggers_alter_triggerconfiguration_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triggerloggers',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
