# Generated by Django 4.2.7 on 2024-03-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0014_alter_triggerloggers_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_tag_setting',
            name='data_type',
            field=models.CharField(choices=[('bit', 'bit'), ('int', 'int'), ('dint', 'dint'), ('intzr', 'intzr'), ('string', 'string'), ('single-precision', 'single-precision'), ('double-precision', 'double-precision')], max_length=100),
        ),
    ]
