# Generated by Django 4.2.7 on 2024-03-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0016_robotcycledatahistory_delete_datahistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadingstationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('hanger_no', models.IntegerField(null=True)),
                ('program_no', models.IntegerField(null=True)),
                ('color_no', models.IntegerField(null=True)),
                ('color_code', models.CharField(max_length=10, null=True)),
                ('part_scanned', models.JSONField(blank=True, default=None, null=True)),
                ('zone', models.JSONField(blank=True, default=None, null=True)),
                ('last_zone', models.IntegerField(null=True)),
                ('live_status', models.IntegerField(null=True)),
                ('quality', models.JSONField(blank=True, default=None, null=True)),
                ('category', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='zonedata2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.CharField(blank=True, max_length=100, null=True)),
                ('degrease_circ_pump', models.BooleanField(blank=True, null=True)),
                ('degrease_heat_pump', models.BooleanField(blank=True, null=True)),
                ('buner', models.BooleanField(blank=True, null=True)),
                ('deg_hot_water_diff_prs', models.IntegerField(blank=True, null=True)),
                ('deg_circ_pump_prs', models.IntegerField(blank=True, null=True)),
                ('deg_circ_flow', models.IntegerField(blank=True, null=True)),
                ('deg_tank_temp', models.IntegerField(blank=True, null=True)),
                ('deg_tank_level', models.IntegerField(blank=True, null=True)),
                ('LoadingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.loadingstationdata')),
            ],
        ),
        migrations.CreateModel(
            name='zonedata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intime', models.CharField(blank=True, max_length=100, null=True)),
                ('outtime', models.CharField(blank=True, max_length=100, null=True)),
                ('pausetime', models.IntegerField(blank=True, null=True)),
                ('LoadingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.loadingstationdata')),
            ],
        ),
    ]
