# Generated by Django 4.2.7 on 2024-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0017_loadingstationdata_zonedata2_zonedata1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingstationdata',
            name='zone',
        ),
    ]
