# Generated by Django 4.2.7 on 2024-03-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integer', '0018_remove_loadingstationdata_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadingstationdata',
            name='part_scanned',
        ),
        migrations.RemoveField(
            model_name='loadingstationdata',
            name='quality',
        ),
        migrations.AddField(
            model_name='loadingstationdata',
            name='color_code_man',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ln_code', models.CharField(blank=True, max_length=100, null=True)),
                ('production_id', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('warehouse_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('LoadingStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integer.loadingstationdata')),
            ],
        ),
    ]
